
export const HERO_SELECT = 'HERO_SELECT';
export const HERO_URL = 'HERO_URL';
export const HERO_SEARCH = 'HERO_SEARCH';

export const ADD_HERO_TEAM = 'ADD_HERO_TEAM';
export const REMOVE_HERO_TEAM = 'REMOVE_HERO_TEAM';

export const ADD_VILLAIN_TEAM = 'ADD_VILLAIN_TEAM'
export const REMOVE_VILLAIN_TEAM = 'REMOVE_VILLAIN_TEAM'